on:
  workflow_call:
    inputs:
      JAVA_VERSION:
        description: 'Java version to use'
        required: true
        default: '17'
        type: string
      DETEKT_RUN_FOLDER:
        description: 'Directory to run detekt on'
        required: true
        default: 'src/main/kotlin'
        type: string
      DETEKT_FILE:
        description: 'Detekt config file'
        required: true
        default: 'detekt-config.yml'
        type: string

name: 🅺 Kotlin Detekt

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ inputs.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Install Detekt and Run it
        run: |
          curl -sSLO https://github.com/detekt/detekt/releases/download/v1.23.3/detekt-cli-1.23.3-all.jar
          mv detekt-cli-1.23.3-all.jar detekt.jar
          chmod +x detekt.jar
          java -jar detekt.jar --input ${{ inputs.DETEKT_RUN_FOLDER}} --config ${{ inputs.DETEKT_FILE }}
        shell: bash
