on: pull_request
name: ":material-eye-check: Changelog check"

jobs:
  build:
    name: ":material-eye-check: Check if the changelog has been updated"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: ":material-eye-check: Check changelog has been updated"
        id: changelogcheck
        if: github.base_ref == 'main'
        run: |
          echo "base ref is main, checking changelog..."
          git fetch
          if [ -z "$(git diff --name-only origin/main | grep CHANGELOG.md)" ]; then
            echo "❌ [FAIL] - Changelog has not been updated"
            exit 1
          else
            echo "✅ [OK] - Changelog has been updated"
          fi
