on: pull_request
name: ":simple-kotlin: Kotlin Spring Boot CI/CD :simple-spring:"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    env:
      KOTLIN_VERSION: ${{ secrets.KOTLIN_VERSION }}
      JAVA_VERSION: ${{ secrets.JAVA_VERSION }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Set up Kotlin
        uses: actions/setup-kotlin@v1
        with:
          kotlin-version: ${{ env.KOTLIN_VERSION }}

      - name: Build and Test Spring Boot Application
        run: |
          ./mvnw clean install

      - name: Run Tests
        run: |
          ./mvnw test
