name: Spring Boot Kotlin CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Kotlin
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: 17

      - name: Build and Test Spring Boot Application
        run: |
          ./mvnw clean install

      - name: Run Tests
        run: |
          ./mvnw test
      - name: Deploy to server
        run: |
          scp build/libs/app.jar user@server:/path/to/deploy
          ssh user@server 'systemctl restart myapp'