name: Flutter Build Android

on:
  push:
    branches:
      - main
  workflow_call:
    inputs:
      working-directory:
        description: 'Working Directory'
        required: true
        type: string
        default: '.'
      flutter-version:
        description: 'Flutter Version'
        required: true
        type: string
        default: '3.22.3'
      save-artifact:
        description: 'Save Artifact'
        required: false
        type: boolean
        default: false
      artifact-name:
        description: 'Artifact Name'
        required: false
        type: string
        default: 'flutter-build'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.flutter-version }}

      - name: Install dependencies
        run: flutter pub get
        working-directory: ${{ inputs.working-directory }}

      - name: Analyze code
        run: flutter analyze
        working-directory: ${{ inputs.working-directory }}

      - name: Run tests
        run: flutter test
        working-directory: ${{ inputs.working-directory }}

      - name: Build for Android
        run: |
          flutter build apk
        working-directory: ${{ inputs.working-directory }}

      - name: Save artifact
        if: ${{ inputs.save-artifact }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.working-directory }}/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 1

