on: 
  workflow_call:
    inputs:
      FLUTTER_VERSION:
        description: 'Flutter Version'
        required: true
        type: string
        default: '3.22.3'


name: 🎯 Dart CI

jobs:
  build:
    name: 🦋 Flutter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.FLUTTER_VERSION }}
        channel: 'stable'

    - name: Show Flutter Version
      run: flutter --version

    - name: Install Dependencies
      run: flutter pub get  

    - name: Analyze Code
      run: flutter analyze

    - name: Run Tests
      run: flutter test
      