on:
  workflow_call:
    inputs:
      FLUTTER_VERSION:
        description: 'Flutter Version'
        required: true
        type: string
        default: '3.17.0'

name: 🔒 Flutter Security

jobs:
  security:
    name: 🔒 Flutter Security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ inputs.FLUTTER_VERSION }}

      - name: Show Flutter Version
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Run Flutter Security Checker
        run: flutter pub global activate flutter_security_checker && flutter pub global run flutter_security_checker
