on: 
  workflow_call:
    inputs:
      flutter-version:
        description: 'Flutter Version'
        required: true
        type: string
        default: '3.22.3'
      working-directory:
        description: 'Working Directory'
        required: true
        type: string
        default: '.'


name: 🎯 Dart CI

jobs:
  build:
    name: 🦋 Flutter
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ inputs.flutter-version }}
        channel: 'stable'

    - name: Show Flutter Version
      run: flutter --version

    - name: Install Dependencies
      run: flutter pub get  
      working-directory: ${{ inputs.working-directory }}

    - name: Analyze Code
      run: flutter analyze
      working-directory: ${{ inputs.working-directory }}

    - name: Run Tests
      run: flutter test
      working-directory: ${{ inputs.working-directory }}
      