on:
    workflow_call:
        inputs:
            java-version:
                description: 'Java version to use'
                required: true
                default: '21'
                type: string
            working-directory:
                description: 'Working Directory'
                required: true
                default: '.'
                type: string

name: 🅺 Kotlin Kover

jobs:
    kover:
        name: Run Kover
        runs-on: ubuntu-latest

        permissions:
            packages: write
            contents: write
            pull-requests: write
            repository-projects: read

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-java@v3
              with:
                  java-version: ${{ inputs.java-version }}
                  distribution: 'temurin'

            - name: Run tests
              run: ./mvnw test
              working-directory: ${{ inputs.working-directory }}

            - name: Generate kover xml
              run: ./mvnw kover:report-xml
              working-directory: ${{ inputs.working-directory }}
                
            - name: Add coverage report to PR
              id: kover
              uses: mi-kas/kover-report@v1
              with:
                path: |
                  ${{ github.workspace }}/${{ inputs.working-directory }}/target/site/kover/report.xml
                title: Code Coverage
                update-comment: true
                min-coverage-overall: 80
                min-coverage-changed-files: 80
                coverage-counter-type: LINE
            