on:
  workflow_call:
    inputs:
      java-version:
        description: 'Java version'
        required: true
        type: string
        default: '17'
      working-directory:
        description: 'Working Directory'
        required: true
        type: string
        default: '.'

name: 🍃 Maven CICD

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Kotlin
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # See 'Supported distributions' for available options
          java-version: ${{ inputs.java-version }}
          cache: 'maven'

      - name: Build with Maven
        run: ./mvnw clean install
        working-directory: ${{ inputs.working-directory }}

      - name: Run Tests
        run: ./mvnw test
        working-directory: ${{ inputs.working-directory }}
