name: 🎯 TypeScript linter

on:
  workflow_call:
    inputs:
      working-directory:
        description: "Répertoire de travail pour exécuter les commandes"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install
        working-directory: ${{ inputs.working-directory }}

      - name: Run ESLint
        run: npm run lint
        working-directory: ${{ inputs.working-directory }}
